name: cardemory
description: Cardemory flutter application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: ^0.10.1
  sqflite: ^2.0.2
  path: ^1.8.0
  # Remote API
#  connectivity: ^0.4.3+7
#  http: ^0.12.0+2
  # Local cache
#  shared_preferences: ^0.5.3+4

dev_dependencies:
  build_runner: ^2.1.8
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0


flutter:
  uses-material-design: true
