name: cardemory
description: Cardemory flutter application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.0
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  logging: ^1.0.2
  path: ^1.8.0
  sqflite: ^2.0.2
  swipe_cards: ^1.0.0
#  shared_preferences: ^0.5.3+4
dev_dependencies:
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/