version: 2
jobs:
  build:
    branches:
      only:
      - dev
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    #      - run:
    #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
    #         command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Tests
        command: ./gradlew lint test
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: app/build/reports
        destination: reports
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: app/build/test-results
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

    # run ui test in test lab
    - run: ./gradlew dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}


    - run: ./gradlew assembleDebug
    - run: ./gradlew assembleAndroidTest

    - run: sudo gcloud config set project <FIREBASE_PROJECT_ID>
    - run: sudo gcloud auth activate-service-account <FIREBASE_SERVICE_ACCOUNT> --key-file ${HOME}/client-secret.json
    - run: sudo gcloud config set account <FIREBASE_SERVICE_ACCOUNT>
    - run: sudo gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus9,version=25 --use-orchestrator
