// Mocks generated by Mockito 5.1.0 from annotations
// in cardemory/test/features/card_set_list/presentation/bloc/card_set_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:cardemory/core/error/failures.dart' as _i5;
import 'package:cardemory/core/usecases/usecase.dart' as _i7;
import 'package:cardemory/features/card_set_list/domain/entities/card_set.dart'
    as _i6;
import 'package:cardemory/features/card_set_list/domain/usecases/get_card_set_list.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetCardSetList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCardSetList extends _i1.Mock implements _i3.GetCardSetList {
  MockGetCardSetList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>> call(
          _i7.NoParams? _) =>
      (super.noSuchMethod(Invocation.method(#call, [_]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.CardSet>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>>);
}
