// Mocks generated by Mockito 5.1.0 from annotations
// in cardemory/test/domain/card_set/usecase/save_card_set_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:cardemory/core/error/failures.dart' as _i5;
import 'package:cardemory/domain/card_set/entity/card_set.dart' as _i6;
import 'package:cardemory/domain/card_set/repository/card_set_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CardSetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardSetRepository extends _i1.Mock implements _i3.CardSetRepository {
  MockCardSetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>> getCardSets() =>
      (super.noSuchMethod(Invocation.method(#getCardSets, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.CardSet>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.CardSet>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CardSet>> saveCardSet(
          _i6.CardSet? cardSet) =>
      (super.noSuchMethod(Invocation.method(#saveCardSet, [cardSet]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.CardSet>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CardSet>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CardSet>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CardSet?>> getCardSet(int? id) =>
      (super.noSuchMethod(Invocation.method(#getCardSet, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.CardSet?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CardSet?>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CardSet?>>);
}
